# Generated by Django 5.1 on 2024-12-09 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='interviewSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('jobRole', models.CharField(max_length=200)),
                ('experience', models.CharField(max_length=200)),
                ('resume', models.TextField()),
                ('interviewDate', models.DateField()),
                ('interviewTime', models.TimeField()),
                ('token', models.CharField(max_length=200)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
