# Generated by Django 5.1 on 2025-05-06 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='accuracy',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='communication',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='evaluation_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='good_fit',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='strengths',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='technical_depth',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='weaknesses',
            field=models.TextField(blank=True, null=True),
        ),
    ]
