# Generated by Django 5.1 on 2025-05-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0002_interviewschedule_accuracy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='cheatingScore',
            field=models.CharField(blank=True, choices=[('normal', 'Normal'), ('suspicious', 'Suspicious'), ('cheating', 'Cheating')], max_length=10, null=True),
        ),
    ]
