# Generated by Django 5.1 on 2025-05-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0003_interviewschedule_cheatingscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='cheatingScore',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
