# Generated by Django 5.1 on 2025-05-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0004_alter_interviewschedule_cheatingscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='token',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
