# Generated by Django 5.1 on 2025-06-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hr', '0005_alter_interviewschedule_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='Assigned_hr',
            field=models.TextField(blank=True, null=True),
        ),
    ]
